[env]
platform = espressif32
board = esp32cam
framework = arduino
board_build.boot = qio
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -mfix-esp32-psram-cache-strategy=memw

[env:diagnostic]
build_src_filter =
  +<diagnostic/**>
  -<web_photo/**>

[env:web_photo]
build_src_filter =
  +<web_photo/**>
  -<diagnostic/**>
